### ISSUE TITLE
Linearizability: SC vs Serializability

### ISSUE THREAD

**Issue by pveentjer** [mwhittaker/papers#5]
Hi Michael,

I was reading the following page:

https://mwhittaker.github.io/papers/html/herlihy1990linearizability.html

And you mention:
```Serializability is analogous to sequential consistency with transactions```

I don't believe this is completely correct. 

For an execution to be SC, it needs to have the same outcome as if the operations were executed in some sequential order and this order is consistent with the PO of each of the threads.

For an execution to be Serializable, it needs to have the same outcome as if the transactions were executed in some sequential order, but unlike SC, PO doesn't need to be preserved.

So if the following set of instructions would be executed:

assume A=0

thread1: tx1: start
thread1: tx1: write A=1
thread1: tx1: commit
thread1: tx2: start
thread1: tx2: read A
thread1: tx2: commit

Then the read of A doesn't need to return 1, i.e. It is allowed for tx2  to be sequenced in front of tx1 and still see the value 0.

https://jepsen.io/consistency/models/serializable

**Comment by mwhittaker** [comment]
Hi Peter! 

You're 100% right. Thanks so much for pointing out that error and explaining it so clearly to me! I updated the notes to point to this issue, so that future readers can benefit from your explanation and example. I'm also happy to hear that someone was reading through these notes. I thought it was just me 🤣 

Best,
Michael

**Comment by pveentjer** [comment]
Your notes were also pretty useful to me. The Linearizability paper is not the easiest paper to read.
